# -*- coding: utf-8 -*-
"""Cross-language golden check: the v2 wire format must be byte-for-byte
identical between the Node broker (broker/src/protocol.js) and this Python
mirror of the self-use relay/protocol.py. The vectors below were generated by
running the real self-use protocol.py; both implementations must reproduce them.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import sys

VECTORS = [
    {
        "name": "request_ascii",
        "payload": {
            "body": "Please review this change",
            "execution_mode": "read",
            "idempotency_key": "dsh:9f2c1a",
            "kind": "request",
            "origin": "dsh",
            "session_ref": "dsh",
            "target": "codex",
            "ttl_seconds": 3600,
        },
        "body_hex": "7b22626f6479223a22506c65617365207265766965772074686973206368616e6765222c22657865637574696f6e5f6d6f6465223a2272656164222c226964656d706f74656e63795f6b6579223a226473683a396632633161222c226b696e64223a2272657175657374222c226f726967696e223a22647368222c2273657373696f6e5f726566223a22647368222c22746172676574223a22636f646578222c2274746c5f7365636f6e6473223a333630307d",
        "signature": "191f619a22bf4d177bfe8f74a1074e5dc4e929e05507269a9584cc2e49513225",
    },
    {
        "name": "request_cjk",
        "payload": {
            "body": "请帮我核查一下这段代码的边界条件",
            "context": "项目路径 D:/workspace/proj，注意不要改动凭据",
            "execution_mode": "write",
            "idempotency_key": "hermes:7e1b",
            "kind": "request",
            "origin": "hermes",
            "session_ref": "hermes",
            "target": "claude",
            "topic": "code-review",
            "ttl_seconds": 1800,
        },
        "body_hex": "7b22626f6479223a22e8afb7e5b8aee68891e6a0b8e69fa5e4b880e4b88be8bf99e6aeb5e4bba3e7a081e79a84e8beb9e7958ce69da1e4bbb6222c22636f6e74657874223a22e9a1b9e79baee8b7afe5be8420443a2f776f726b73706163652f70726f6aefbc8ce6b3a8e6848fe4b88de8a681e694b9e58aa8e587ade68dae222c22657865637574696f6e5f6d6f6465223a227772697465222c226964656d706f74656e63795f6b6579223a226865726d65733a37653162222c226b696e64223a2272657175657374222c226f726967696e223a226865726d6573222c2273657373696f6e5f726566223a226865726d6573222c22746172676574223a22636c61756465222c22746f706963223a22636f64652d726576696577222c2274746c5f7365636f6e6473223a313830307d",
        "signature": "b9c1be8b482d5b8e520685528f453722e2828c346f1e7c066d2178afe1cafb92",
    },
    {
        "name": "reply",
        "payload": {
            "body": "已审查，结论：无问题。\n风险：无。",
            "idempotency_key": "reply:abc123def456",
            "kind": "reply",
            "origin": "codex",
            "parent_id": "abc123def456",
            "session_ref": "dsh",
            "target": "dsh",
            "ttl_seconds": 300,
        },
        "body_hex": "7b22626f6479223a22e5b7b2e5aea1e69fa5efbc8ce7bb93e8aebaefbc9ae697a0e997aee9a298e380825c6ee9a38ee999a9efbc9ae697a0e38082222c226964656d706f74656e63795f6b6579223a227265706c793a616263313233646566343536222c226b696e64223a227265706c79222c226f726967696e223a22636f646578222c22706172656e745f6964223a22616263313233646566343536222c2273657373696f6e5f726566223a22647368222c22746172676574223a22647368222c2274746c5f7365636f6e6473223a3330307d",
        "signature": "4417643795f62017d2a0bd509ffa641e17c035f00930f3eec7e636f0f7f4d7d1",
    },
]

AGENT = "test-agent"
SECRET = "s3cret"
METHOD = "POST"
PATH = "/v1/messages"
TS = "1755250000"


def canonical_body(payload):
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode("utf-8")


def make_signature(agent, secret, method, path, timestamp, body):
    digest = hashlib.sha256(body).hexdigest()
    signed = "\n".join((agent, timestamp, method.upper(), path, digest)).encode("utf-8")
    return hmac.new(secret.encode("utf-8"), signed, hashlib.sha256).hexdigest()


def main() -> int:
    failures = 0
    for vector in VECTORS:
        body = canonical_body(vector["payload"])
        if body.hex() != vector["body_hex"]:
            print(f"FAIL {vector['name']}: canonical body mismatch")
            failures += 1
            continue
        signature = make_signature(AGENT, SECRET, METHOD, PATH, TS, body)
        if signature != vector["signature"]:
            print(f"FAIL {vector['name']}: signature mismatch")
            failures += 1
            continue
        print(f"ok {vector['name']}")
    if failures:
        print(f"{failures} golden vector(s) FAILED")
        return 1
    print("all golden vectors ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
