#!/usr/bin/env node
/**
 * dsh-agent-relay setup — one-command initialization, start, and self-check.
 *
 *   node setup/setup.js init      generate broker/config.yaml (with a random secret)
 *   node setup/setup.js start     start the broker (foreground)
 *   node setup/setup.js selfcheck verify configuration and broker connectivity
 *
 * The secret is generated locally (crypto.randomBytes) and never leaves your
 * machine unless you copy it to remote agents yourself.
 */
import { randomBytes } from 'node:crypto'
import { existsSync, writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawn } from 'node:child_process'
import { loadConfig, normalizeConfig } from '../broker/src/config.js'

const here = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(here, '..')
const BROKER_DIR = join(ROOT, 'broker')
const CONFIG_PATH = join(BROKER_DIR, 'config.yaml')
const PID_PATH = join(BROKER_DIR, 'data', 'broker.pid')

const CONFIG_TEMPLATE = (secret) => `# dsh-agent-relay broker configuration (generated by setup.js init).
# NEVER commit this file — it contains your shared secret.

broker:
  host: 127.0.0.1          # loopback by default; use 0.0.0.0 only behind TLS
  port: 19121
  secret: ${secret}
  storage: sqlite          # sqlite by default; set jsonl for Node <22.13 without SQLite
  rateLimitLoopback: 600
  rateLimitRemote: 120
  messageTtlDays: 7
  persist: true
  dataDir: ./data

security:
  lockAfterFailures: 5
  lockMinutes: 5
`;

function runInit() {
  if (existsSync(CONFIG_PATH)) {
    console.log('config.yaml already exists — keeping it (re-run with "rm broker/config.yaml" first to regenerate).')
  } else {
    mkdirSync(BROKER_DIR, { recursive: true })
    writeFileSync(CONFIG_PATH, CONFIG_TEMPLATE(randomBytes(32).toString('hex')), 'utf8')
    console.log('wrote broker/config.yaml with a freshly generated secret.')
  }
  console.log(`
Next steps:
  1. Start the broker:          node setup/setup.js start
  2. Configure each agent with the same secret:
       dsh plugin:   DSH_RELAY_SECRET=<secret>  (env) or plugin settings
       CLI client:   node adapters/cli/relay.mjs peers --agent alpha --secret <secret>
       Python:       RelayClient(broker_url="http://127.0.0.1:19121", agent="beta", secret="<secret>")
  3. Verify:        node setup/setup.js selfcheck
Read docs/DEPLOY.md for the full guide.`)
}

function runStart() {
  if (!existsSync(CONFIG_PATH)) {
    console.error('broker/config.yaml missing — run "node setup/setup.js init" first.')
    process.exit(1)
  }
  mkdirSync(dirname(PID_PATH), { recursive: true })
  const child = spawn(process.execPath, [join(BROKER_DIR, 'src', 'index.js'), '--config', CONFIG_PATH], {
    stdio: 'inherit',
    cwd: BROKER_DIR,
  })
  writeFileSync(PID_PATH, String(child.pid), 'utf8')
  console.log(`broker started (pid ${child.pid}) — Ctrl+C to stop`)
  child.on('exit', (code) => {
    try { readFileSync(PID_PATH) } catch { /* already gone */ }
    process.exit(code ?? 0)
  })
}

async function runSelfcheck() {
  const problems = []
  // Resolve the broker URL from config so a custom host/port is checked
  // exactly like the broker itself would bind (reusing the broker's loader
  // keeps this in sync with src/config.js — a config that passes here will
  // also boot the broker, and vice versa).
  let brokerUrl = 'http://127.0.0.1:19121/'
  if (!existsSync(CONFIG_PATH)) {
    problems.push('broker/config.yaml missing — run "node setup/setup.js init"')
  } else {
    try {
      const cfg = normalizeConfig(loadConfig(CONFIG_PATH))
      brokerUrl = `http://${cfg.host}:${cfg.port}/`
      if (!/^[0-9a-f]{16,}$/.test(cfg.secret)) problems.push('broker.secret looks weak or unset')
    } catch (e) {
      problems.push(`broker/config.yaml invalid: ${e.message}`)
    }
  }
  let brokerInfo = null
  try {
    const res = await fetch(brokerUrl, { signal: AbortSignal.timeout(3000) })
    brokerInfo = await res.json()
  } catch {
    problems.push(`broker not reachable at ${brokerUrl} (start it with "node setup/setup.js start")`)
  }
  if (brokerInfo && brokerInfo.protocol !== '1.0') {
    problems.push(`broker protocol mismatch: ${brokerInfo.protocol ?? 'unknown'}`)
  }
  console.log('selfcheck results:')
  if (brokerInfo) console.log(`  broker: ${brokerInfo.broker} ${brokerInfo.version} (protocol ${brokerInfo.protocol}) — OK`)
  for (const p of problems) console.log(`  FAIL: ${p}`)
  console.log(problems.length ? `${problems.length} problem(s) found` : '  all checks passed')
  process.exit(problems.length ? 1 : 0)
}

const cmd = process.argv[2]
switch (cmd) {
  case 'init': runInit(); break
  case 'start': runStart(); break
  case 'selfcheck': runSelfcheck().catch((e) => { console.error(e); process.exit(1) }); break
  default:
    console.error('usage: node setup/setup.js <init|start|selfcheck>')
    process.exit(2)
}
